--- #### STREAMLIT ROLE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS T_E_streamlit_role;
USE ROLE useradmin;

USE ROLE SECURITYADMIN;



--- #### GRANTING ROLES
GRANT ROLE T_E_streamlit_role TO USER ricky_user;
GRANT ROLE T_E_streamlit_role TO USER rajneet_user;
GRANT ROLE T_E_streamlit_role TO USER kristofer_user;
GRANT ROLE T_E_streamlit_role TO USER jassef;
GRANT ROLE T_E_streamlit_role to user T_E_streamlit;

--- #### MARTS LAYER GRANTS
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE T_E_streamlit_role;
GRANT USAGE ON DATABASE ENGINEER_ADS TO ROLE T_E_streamlit_role;
GRANT USAGE ON SCHEMA engineer_ads.marts TO ROLE T_E_streamlit_role;
GRANT SELECT ON ALL TABLES IN SCHEMA ENGINEER_ADS.MARTS TO ROLE T_E_streamlit_ROLE;
GRANT SELECT ON ALL views IN SCHEMA ENGINEER_ADS.MARTS TO ROLE T_E_streamlit_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ENGINEER_ADS.MARTS TO ROLE T_E_streamlit_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ENGINEER_ADS.MARTS TO ROLE T_E_streamlit_ROLE;

--- #### TESTING
USE ROLE T_E_STREAMLIT_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ENGINEER_ADS;
SHOW TABLES IN Marts;
SHOW VIEWS IN Marts;

--- #### SHOW GRANTS

USE ROLE SECURITYADMIN;
SHOW GRANTS TO ROLE t_e_streamlit_role;
SHOW GRANTS ON SCHEMA ENGINEER_ADS.MARTS;