USE ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS Engineer_ads;

USE DATABASE ENGINEER_ADS;

CREATE SCHEMA IF NOT EXISTS Staging;

DROP SCHEMA Staging;

CREATE SCHEMA IF NOT EXISTS Warehouse;

CREATE SCHEMA IF NOT EXISTS Marts;

